general:
  server_name: "VPS-Website-DEV"
  check_interval_seconds: 60
  host_disk_mount_path: "/hostfs"

discord:
  webhook_url: "__DISCORD_WEBHOOK__"
  repeat_alert_after_minutes: 60

system:
  disk_usage_threshold_percent: 70
  memory_usage_threshold_percent: 90
  cpu_load_threshold_percent: 80

docker:
  grace_period_seconds: 60  # Don't alert if container is down for less than this (e.g., during deployments)
  containers:
    - "frontend-dev"

functional:
  http_checks:
    - name: "Directus API Dev"
      url: "http://directus:8055/server/ping"
    - name: "Frontend Dev"
      url: "http://frontend-dev:3000"
  # TCP Check verwijderd ivm netwerk isolatie
