services:
  wiki:
    image: requarks/wiki:2
    container_name: samuwiki
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - proxy-network
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: samuwiki-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs
      DB_NAME: wiki
    volumes:
      - ./config:/wiki/config
      - ./data:/wiki/data
  db:
    image: postgres:15
    container_name: samuwiki-db
    restart: unless-stopped
    networks:
      - proxy-network
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijs
    volumes:
      - ./db-data:/var/lib/postgresql/data
networks:
  proxy-network:
    external: true
