services:
  db:
    image: postgres:15
    container_name: directus_db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
    networks:
      - internal_backend

  directus:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/salvemundi/directus:dev
    container_name: directus
    restart: unless-stopped
    env_file: .env
    environment:
      - KEY=${KEY}
      - SECRET=${SECRET}
      - PUBLIC_URL=${PUBLIC_URL}
      - PORT=8055
      - CORS_ORIGIN=${CORS_ORIGIN}
      - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_CLIENT=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      # Volledige set variabelen voor UI-activering en custom endpoint
      - AUTH_PROVIDERS=microsoft
      - AUTH_MICROSOFT_DRIVER=openid
      - AUTH_MICROSOFT_CLIENT_ID=${AUTH_MICROSOFT_CLIENT_ID}
      - AUTH_MICROSOFT_CLIENT_SECRET=${AUTH_MICROSOFT_CLIENT_SECRET}
      - AUTH_MICROSOFT_ISSUER_URL=${AUTH_MICROSOFT_ISSUER_URL}
      - AUTH_MICROSOFT_SCOPE=${AUTH_MICROSOFT_SCOPE}
      - AUTH_MICROSOFT_IDENTIFIER_KEY=${AUTH_MICROSOFT_IDENTIFIER_KEY}
      - AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION=true
      - AUTH_MICROSOFT_DEFAULT_ROLE_ID=${AUTH_MICROSOFT_DEFAULT_ROLE_ID}
      - AUTH_MICROSOFT_TENANT_ID=${AUTH_MICROSOFT_TENANT_ID}
      - 'AUTH_ENTRA_FIELDS_MAPPING={"email": "userPrincipalName", "first_name": "givenName", "last_name": "surname"}'

    volumes:
      - directus_uploads:/directus/uploads
    networks:
      - proxy-network
      - internal_backend
    depends_on:
      - db

volumes:
  postgres_app_data:
  directus_uploads:

networks:
  proxy-network:
    external: true
  internal_backend:
    driver: bridge