general:
  server_name: "VPS-Website-PROD"
  check_interval_seconds: 60
  host_disk_mount_path: "/hostfs"

discord:
  webhook_url: "__DISCORD_WEBHOOK__"
  repeat_alert_after_minutes: 30

system:
  disk_usage_threshold_percent: 85
  memory_usage_threshold_percent: 90
  cpu_load_threshold_percent: 90

docker:
  containers:
    - "npm"
    - "directus-prod"
    - "postgres-prod"
    - "website-prod"
    - "vaultwarden"

functional:
  http_checks:
    - name: "Website V6 Prod"
      url: "http://website-prod:3000"
