general:
  server_name: "VPS-Website-PROD"
  check_interval_seconds: 60
  host_disk_mount_path: "/hostfs"

discord:
  webhook_url: "__DISCORD_WEBHOOK__"
  repeat_alert_after_minutes: 30

system:
  disk_usage_threshold_percent: 70
  memory_usage_threshold_percent: 90
  cpu_load_threshold_percent: 80

docker:
  containers:
    - "npm"
    - "frontend-latest"

functional:
  http_checks:
    - name: "Website V6 Prod"
      url: "http://frontend-latest:3000"
  # TCP Check verwijderd ivm netwerk isolatie
