name: Deploy Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to development directory
            cd /opt/salvemundi/dev

            # Update code
            git pull origin develop

            # Generate .env file dynamically from GitHub Secrets and Variables
            echo "DB_USER=${{ secrets.DB_USER }}" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "DIRECTUS_KEY=${{ secrets.DIRECTUS_KEY }}" >> .env
            echo "DIRECTUS_SECRET=${{ secrets.DIRECTUS_SECRET }}" >> .env
            echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
            echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
            echo "PUBLIC_URL=${{ secrets.PUBLIC_URL }}" >> .env
            echo "SERVICE_SECRET=${{ secrets.SERVICE_SECRET }}" >> .env
            echo "DIRECTUS_ADMIN_TOKEN=${{ secrets.DIRECTUS_ADMIN_TOKEN }}" >> .env
            echo "INTERNAL_DIRECTUS_URL=${{ vars.INTERNAL_DIRECTUS_URL }}" >> .env
            echo "MOLLIE_API_KEY=${{ secrets.MOLLIE_API_KEY }}" >> .env
            echo "NEXT_PUBLIC_DIRECTUS_URL=${{ vars.NEXT_PUBLIC_DIRECTUS_URL }}" >> .env
            echo "MS_GRAPH_CLIENT_ID=${{ secrets.EMAIL_CLIENT_ID }}" >> .env
            echo "MS_GRAPH_CLIENT_SECRET=${{ secrets.EMAIL_CLIENT_SECRET }}" >> .env
            echo "MS_GRAPH_TENANT_ID=${{ secrets.MS_GRAPH_TENANT_ID }}" >> .env
            echo "MS_GRAPH_SENDER_UPN=${{ secrets.EMAIL_SENDER_ADDR }}" >> .env
            echo "MS_GRAPH_SENDER_NAME=${{ secrets.EMAIL_SENDER_NAME }}" >> .env

            # Deploy services
            docker compose up -d --build
