services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      # Dit zijn de ENIGE poorten die naar het web openstaan
      - '80:80'    # Standaard HTTP
      - '443:443'  # Standaard HTTPS
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
# Koppel aan het netwerk dat we net hebben gemaakt
networks:
  default:
      name: proxy-network
      external: true
